title: saktibuana
remote_theme: pmarsceill/just-the-docs
search_enabled: true
# For the upper right navigation
aux_links:
    "Contact @saktibuana":
      - "http://s.id/saktibuana"
color_scheme: "light"
#color_scheme: "dark"
