title: http://s.id/saktibuana
remote_theme: pmarsceill/just-the-docs
search_enabled: true
# For the upper right navigation
aux_links:
    "Contact Me":
      - "http://s.id/saktibuana"
color_scheme: "dark"
